services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ${DOCKER_VOLUME}/minio_vol:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  mongod1:
    container_name: mongod1
    hostname: mongod1
    image: mongodb/mongodb-community-server
    ports:
      - 27018:27018
    volumes:
      - ${DOCKER_VOLUME}/mongo1_vol:/data/db:z
      - ${PWD}/replica.key:/data/replica.key
      - ./mongo-init/init-user.js:/docker-entrypoint-initdb.d/init-user.js
      - ./scripts/init-mongod1.sh:/init-mongod1.sh
    entrypoint: ["/bin/bash", "/init-mongod1.sh"]
    networks:
      - mongo_net
    restart: unless-stopped

  mongod2:
    container_name: mongod2
    hostname: mongod2
    image: mongodb/mongodb-community-server
    ports:
      - 27019:27019
    volumes:
      - ${DOCKER_VOLUME}/mongo2_vol:/data/db
      - ${PWD}/replica.key:/data/replica.key
      - ./scripts/init-mongod2.sh:/init-mongod2.sh
    networks:
      - mongo_net
    entrypoint: ["/bin/bash", "/init-mongod2.sh"]
    restart: unless-stopped

  mongod3:
    container_name: mongod3
    hostname: mongod3
    image: mongodb/mongodb-community-server
    ports:
      - 27020:27020
    volumes:
      - ${DOCKER_VOLUME}/mongo3_vol:/data/db
      - ${PWD}/replica.key:/data/replica.key
      - ./scripts/init-mongod3.sh:/init-mongod3.sh
    networks:
      - mongo_net
    entrypoint: ["/bin/bash", "/init-mongod3.sh"]
    restart: unless-stopped

  mongod4:
    container_name: mongod4
    hostname: mongod4
    image: mongodb/mongodb-community-server
    ports:
      - 27021:27021
    volumes:
      - ${DOCKER_VOLUME}/mongo4_vol:/data/db
      - ${PWD}/replica.key:/data/replica.key
      - ./scripts/init-mongod4.sh:/init-mongod4.sh
    networks:
      - mongo_net
    entrypoint: ["/bin/bash", "/init-mongod4.sh"]
    restart: unless-stopped

  mongod-init:
    container_name: mongod-init
    image: mongodb/mongodb-community-server
    depends_on:
      - mongod1
      - mongod2
      - mongod3
      - mongod4
    volumes:
      - ./mongo-init/init-replica.js:/mongo-init/init-replica.js:ro
      - ./scripts/init-replica.sh:/init-replica.sh:ro
    networks:
      - mongo_net
    entrypoint: ["/bin/sh", "-c", "sleep 15 & /init-replica.sh"]

networks:
  mongo_net:
    driver: bridge
