org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Enable parallel & optimized gradle builds
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# Disable legacy R class generation (faster)
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Faster Kotlin (especially with KSP)
kotlin.incremental=true
kotlin.code.style=official
android.defaults.buildfeatures.buildconfig=true
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.13-bin.zip"