// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4FDXFZca3t2iHyJKoBlkwim1G_YqQM4',
    appId: '1:391381684969:android:f036d13cc8c59652b2d678',
    messagingSenderId: '391381684969',
    projectId: 'pixl-caf6b',
    storageBucket: 'pixl-caf6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCngP-9kfI_Dq4u1DS2xiIEihhNbYmVKLc',
    appId: '1:391381684969:ios:c8c5ceddaadbe373b2d678',
    messagingSenderId: '391381684969',
    projectId: 'pixl-caf6b',
    storageBucket: 'pixl-caf6b.firebasestorage.app',
    iosBundleId: 'com.example.pixlClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCngP-9kfI_Dq4u1DS2xiIEihhNbYmVKLc',
    appId: '1:391381684969:ios:39901155f8b948a7b2d678',
    messagingSenderId: '391381684969',
    projectId: 'pixl-caf6b',
    storageBucket: 'pixl-caf6b.firebasestorage.app',
    iosBundleId: 'com.nativebridge.pixl',
  );

}